// Mocks generated by Mockito 5.4.0 from annotations
// in musicday_mobile/test/auth/interceptors/token_interceptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:musicday_mobile/auth/models/session.dart' as _i5;
import 'package:musicday_mobile/auth/repositories/auth_session_repository.dart'
    as _i3;
import 'package:musicday_mobile/core/logging/logger.dart' as _i2;
import 'package:musicday_mobile/core/logging/logger_factory.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSessionRepository extends _i1.Mock
    implements _i3.AuthSessionRepository {
  @override
  _i4.Stream<_i5.Session?> get currentSession => (super.noSuchMethod(
        Invocation.getter(#currentSession),
        returnValue: _i4.Stream<_i5.Session?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.Session?>.empty(),
      ) as _i4.Stream<_i5.Session?>);
  @override
  set currentSession(_i4.Stream<_i5.Session?>? _currentSession) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentSession,
          _currentSession,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> saveSession(_i5.Session? session) => (super.noSuchMethod(
        Invocation.method(
          #saveSession,
          [session],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<String?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
  @override
  _i4.Future<void> deleteSession() => (super.noSuchMethod(
        Invocation.method(
          #deleteSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [LoggerFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerFactory extends _i1.Mock implements _i6.LoggerFactory {
  @override
  _i2.Logger create(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [tag],
        ),
        returnValue: _FakeLogger_0(
          this,
          Invocation.method(
            #create,
            [tag],
          ),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.method(
            #create,
            [tag],
          ),
        ),
      ) as _i2.Logger);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i2.Logger {
  @override
  void debug(String? message) => super.noSuchMethod(
        Invocation.method(
          #debug,
          [message],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void warn(
    String? message, {
    dynamic exception,
    StackTrace? stacktrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #warn,
          [message],
          {
            #exception: exception,
            #stacktrace: stacktrace,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void error(
    String? message, {
    dynamic exception,
    StackTrace? stacktrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #exception: exception,
            #stacktrace: stacktrace,
          },
        ),
        returnValueForMissingStub: null,
      );
}
